name: "Aniflix"
services:
  consumet:
    image: riimuru/consumet-api:latest
    restart: always
    networks:
      - aniflix
    ports:
      - "3001:3000"
#    environment:
#      - REDIS_HOST=${CONSUMET_REDIS_HOST}
#      - REDIS_PORT=${CONSUMET_REDIS_PORT}
#      - REDIS_PASSWORD=${CONSUMET_REDIS_PASSWORD}
#      - REDIS_USERNAME=${CONSUMET_REDIS_USERNAME}

#  redis:
#    image: bitnami/redis:latest
#    restart: always
#    networks:
#      - aniflix
#    ports:
#      - '6379:6379'
#    expose:
#      - '6379'
#    volumes:
#      - ./data/redis/users.acl:/opt/bitnami/redis/mounted-etc/users.acl
#    environment:
#      - REDIS_PASSWORD=${REDIS_PASSWORD}
#      - REDIS_ACLFILE=${REDIS_ACLFILE}
#
#  postgresql:
#    image: bitnami/postgresql:latest
#    restart: always
#    networks:
#      - aniflix
#    ports:
#      - '5432:5432'
#    expose:
#      - '5432'
#    volumes:
#      - ./data/postgresql:/bitnami/postgresql
#    environment:
#      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#      - POSTGRES_USER=${POSTGRES_USER}
#      - POSTGRES_DB=${POSTGRES_DB}
#
#volumes:
#  redis:
#  postgresql:
#    driver: local

networks:
  aniflix:
    driver: bridge
