# ======= APPLICATION CONFIGURATION =======
application:
  email:
    host: ${EMAIL_HOST:localhost}
    port: ${EMAIL_PORT:2500}
    address: ${EMAIL_ADDRESS:no-reply@localhost}
    username: ${EMAIL_USERNAME:no-login@localhost.com}
    password: ${EMAIL_PASSWORD:password}
    protocol: smtp
    encoding: UTF-8

  security:
    jwt:
      lifetime: ${JWT_LIFETIME_SECONDS:900}
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS:*}

# ======= CONSUMET CONFIGURATION =======
consumet:
  url: ${CONSUMET_URL:https://consumet.com}

# ======= MANAGEMENT ENDPOINTS =======
management:
  endpoints:
    web:
      exposure.include: health,metrics,prometheus
      base-path: /api/actuator
  otlp:
    metrics:
      export:
        url: ${OTLP_METRICS_EXPORT_URL:http://0.0.0.0:4318/v1/metrics}
        step: 10s
    tracing:
      endpoint: ${OTLP_TRACING_ENDPOINT:http://0.0.0.0:4318/v1/traces}
  tracing:
    sampling:
      probability: 1.0

# ====== SERVER CONFIG ======
server:
  port: 8080

tomcat:
  ajp:
    enabled: ${TOMCAT_AJP_ENABLED:true}
    port: ${TOMCAT_AJP_PORT:8009}
    secretRequired: ${TOMCAT_AJP_SECRET_REQUIRED:false}
    secret: ${TOMCAT_AJP_SECRET:6qyuET3rNuzYRBtrBQjh8zCe}

# ======= LOGGING CONFIG =======
logging:
  config: ${LOGGING_CONFIG:./config/logback-spring.xml}

# ======= SPRINGDOC CONFIGURATION <https://springdoc.org/> =======
springdoc:
  show-actuator: true
  pre-loading-enabled: true
  show-login-endpoint: true
  enable-spring-security: true
  swagger-ui:
    disable-swagger-default-url: true
    path: /api/public/docs/openapi.html
  api-docs:
    path: /api/public/docs

# ======= SPRING CONFIGURATION =======
spring:
  profiles.include: ${SPRING_PROFILES_INCLUDE:development}

  application:
    version: 0.1.0
    name: ${SPRING_APPLICATION_NAME:aniflix-development}
    url: ${SPRING_APPLICATION_URL:http://localhost:8080}

  cache:
    type: redis
    redis:
      time-to-live: 300000
      enable-statistics: true
  data:
    redis:
      host: ${SPRING_REDIS_HOST:redis}
      port: ${SPRING_REDIS_PORT:6379}

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${SPRING_DATASOURCE_URL:jdbc:mariadb://mariadb:3306/test}
    username: ${SPRING_DATASOURCE_USERNAME:username}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.mariadb.jdbc.Driver

  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true

  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        enable_lazy_load_no_trans: true
        batch_versioned_data: true
        jdbc.batch_size: 100
        order_updates: true
        order_inserts: true

# ======= HAWAII AUTOCONFIGURATION OVERRIDE =======
hawaii:
  async:
    configuration: ${ASYNC_CONFIG:./config/async-config.yml}
  crypto:
    enabled: false
  logging:
    filters:
      transaction-id:
        enabled: true
      request-id:
        enabled: true
